/*
 * API Actores
 * Documentación de la API de actores
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ActorIdGet200Response
 */
public class ActorIdGet200ResponseTest {
    private final ActorIdGet200Response model = new ActorIdGet200Response();

    /**
     * Model tests for ActorIdGet200Response
     */
    @Test
    public void testActorIdGet200Response() {
        // TODO: test ActorIdGet200Response
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nombre'
     */
    @Test
    public void nombreTest() {
        // TODO: test nombre
    }

    /**
     * Test the property 'genero'
     */
    @Test
    public void generoTest() {
        // TODO: test genero
    }

    /**
     * Test the property 'nacionalidad'
     */
    @Test
    public void nacionalidadTest() {
        // TODO: test nacionalidad
    }

    /**
     * Test the property 'peliculaMasExitosa'
     */
    @Test
    public void peliculaMasExitosaTest() {
        // TODO: test peliculaMasExitosa
    }

    /**
     * Test the property 'premios'
     */
    @Test
    public void premiosTest() {
        // TODO: test premios
    }

}
